### ISSUE TITLE
Fetch of an entire repository crashes in the top/subrepoexapander codepath

### ISSUE THREAD

**Issue by stagnation** [meroton/git-toprepo#10]
This is often a mistake when copy-pasting the gerrit fetch command of a special ref.
Though it stands to reason that one should be able to fetch all refs in a repository.
Either way we should avoid crashing, would prefer an error if the fetch command is used with incorrect arguments.
```
$ git toprepo git fetch ssh://$USER@gerrit-server.internal/repository
Running   git -C . fetch --quiet ssh://$USER@gerrit-server.internal/repository +refs/meta/git-toprepo:refs/toprepo/config/default
Running   git -C .git/repos/repository fetch --prune --prune-tags --tags ssh://$USER@gerrit-server.internal/repository +refs/heads/*:refs/heads/*
Running   git -C . fetch --quiet --no-tags --prune /home/$USER/path/to/top/.git/repos/repository +refs/*:refs/repos/repository/*
Traceback (most recent call last):
  File "/home/$USER/bin/git-toprepo", line 2644, in <module>
    sys.exit(main())
  File "/home/$USER/bin/git-toprepo", line 2634, in main
    returncode = args.func(args=args)
  File "/home/$USER/bin/git-toprepo", line 2351, in main_fetch
    if not expander.expand_toprepo(top_refs=["--all"], allow_fetching=True):
AttributeError: 'SubrepoCommitExpander' object has no attribute 'expand_toprepo'
```

**Comment by moroten** [comment]
Should be solved in the rust version. Please reopen if still a problem.
